SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- =============================================
-- Author:		Bryan Eddy
-- Create date: 7/7/2017
-- Description:	Pull data from setup tables  
-- Date Modified: 7/28/2017
-- Modifications: Updated to pull from only 3 tables.  Others should remain static
-- =============================================
CREATE PROCEDURE [dbo].[usp_GetSetupData]
AS
	SET NOCOUNT ON;
--BEGIN TRY 
DELETE FROM Setup.tblAttributes;
DELETE FROM Setup.tblSetup;
DELETE FROM Setup.tblSetupAttributes;
--DELETE FROM Setup.tblAttributesGroup;
--DELETE FROM Setup.[tblProcessMachines]



INSERT INTO Setup.tblAttributes([AttributeID]
      ,[ProcessID]
      ,[AttrIneffectiveDate]
      ,[AttrEffectiveDate]
      ,[AttributeGroupID]
      ,[AttributeDesc]
      ,[AttributeName]
      ,[AttributeUOM]
      ,[LimitToList]
      ,[Active]
      ,[ListSource]
      ,[AttributeViewOrder]
      ,[AttributeDataType]
      ,[ListSourceColumnCount]
      ,[AttributeComments]
      ,[ToleranceReq]
      ,[ToleranceUOM]
      ,[DefaultValue]
      ,[DefaultMinTol]
      ,[DefaultMaxTol]
      ,[DefaultMinValue]
      ,[DefaultMaxValue]
      ,[DefaultMinValueTol]
      ,[DefaultMaxValueTol]
      ,[DefaultPrintOnSetup]
      ,[AddToDesc]
      ,[ApprovalReq]
      ,[ScheduleNotice]
      ,[OracleNotice]
      ,[EditAllowed]
      ,[RecordResults]
      ,[SigDigits]
      ,[ReferenceOnly]
      ,[FormulaBased]
      ,[ToleranceType])
SELECT [AttributeID]
      ,[ProcessID]
      ,[AttrIneffectiveDate]
      ,[AttrEffectiveDate]
      ,[AttributeGroupID]
      ,[AttributeDesc]
      ,[AttributeName]
      ,[AttributeUOM]
      ,[LimitToList]
      ,[Active]
      ,[ListSource]
      ,[AttributeViewOrder]
      ,[AttributeDataType]
      ,[ListSourceColumnCount]
      ,[AttributeComments]
      ,[ToleranceReq]
      ,[ToleranceUOM]
      ,[DefaultValue]
      ,[DefaultMinTol]
      ,[DefaultMaxTol]
      ,[DefaultMinValue]
      ,[DefaultMaxValue]
      ,[DefaultMinValueTol]
      ,[DefaultMaxValueTol]
      ,[DefaultPrintOnSetup]
      ,[AddToDesc]
      ,[ApprovalReq]
      ,[ScheduleNotice]
      ,[OracleNotice]
      ,[EditAllowed]
      ,[RecordResults]
      ,[SigDigits]
      ,[ReferenceOnly]
      ,[FormulaBased]
      ,[ToleranceType]
FROM  [NAASPB-PRD04\SQL2014].Premise.Setup.tblAttributes;

INSERT INTO Setup.tblSetup([SetupID]
      ,[ProcessID]
      ,[SetupNumber]
      ,[SetupDesc]
      ,[EffectiveDate]
      ,[IneffectiveDate]
      ,[EnteredBy]
      ,[EnteredOnDate]
      ,[Comments]
      ,[ApprovedOnDate]
      ,[ApprovedBy]
      ,[Status]
      ,[MachineID])
SELECT [SetupID]
      ,[ProcessID]
      ,[SetupNumber]
      ,[SetupDesc]
      ,[EffectiveDate]
      ,[IneffectiveDate]
      ,[EnteredBy]
      ,[EnteredOnDate]
      ,[Comments]
      ,[ApprovedOnDate]
      ,[ApprovedBy]
      ,[Status]
      ,[MachineID]
FROM [NAASPB-PRD04\SQL2014].Premise.Setup.tblSetup;

INSERT INTO Setup.tblSetupAttributes ([SetupID]
      ,[AttributeID]
      ,[IneffectiveDate]
      ,[ProcessID]
      ,[MachineID]
      ,[EffectiveDate]
      ,[AttributeValue]
      ,[RequiredNew]
      ,[RequiredEdit]
      ,[ViewNew]
      ,[ViewEdit]
      ,[Comments]
      ,[MinTol]
      ,[MaxTol]
      ,[MachineSpecific]
      ,[MinValue]
      ,[MaxValue]
      ,[EnteredBy]
      ,[EnteredOnDate]
      ,[PrintOnSetup]
      ,[ApprovedBy]
      ,[ApprovedOnDate])
SELECT [SetupID]
      ,[AttributeID]
      ,[IneffectiveDate]
      ,[ProcessID]
      ,[MachineID]
      ,[EffectiveDate]
      ,[AttributeValue]
      ,[RequiredNew]
      ,[RequiredEdit]
      ,[ViewNew]
      ,[ViewEdit]
      ,[Comments]
      ,[MinTol]
      ,[MaxTol]
      ,[MachineSpecific]
      ,[MinValue]
      ,[MaxValue]
      ,[EnteredBy]
      ,[EnteredOnDate]
      ,[PrintOnSetup]
      ,[ApprovedBy]
      ,[ApprovedOnDate]
FROM [NAASPB-PRD04\SQL2014].Premise.Setup.tblSetupAttributes;
--END TRY

--BEGIN CATCH

--END CATCH;
--GO

--INSERT INTO Setup.tblAttributesGroup
--SELECT *
--FROM [NAASPB-PRD04\SQL2014].Premise.Setup.tblAttributesGroup

--INSERT INTO [Setup].[tblProcessMachines]([ProcessID]
--      ,[MachineID]
--      ,[MachineNumber]
--      ,[MachineRanking]
--      ,[Active]
--      ,[Comments]
--      ,[AddScheduleDates]
--      ,[Uptime]
--      ,[RightTheFirstTime]
--      ,[MachineShiftStartTime]
--      ,[MachineShiftEndTime]
--      ,[MachineStartDelay]
--      ,[PMDefaultTime]
--      ,[DownTime]
--      ,[ProcessTimeExtension]
--      ,[MachineCount]
--      ,[ProcessTimeDelay]
--      ,[IncludeInReport]
--      ,[PreactorMachineID]
--      ,[ProcessMachineID]
--      ,[PreactorProcessID]
--      ,[PreactorMachineNumber]
--      ,[PlanetTogetherMachineNumber])
--SELECT [ProcessID]
--      ,[MachineID]
--      ,[MachineNumber]
--      ,[MachineRanking]
--      ,[Active]
--      ,[Comments]
--      ,[AddScheduleDates]
--      ,[Uptime]
--      ,[RightTheFirstTime]
--      ,[MachineShiftStartTime]
--      ,[MachineShiftEndTime]
--      ,[MachineStartDelay]
--      ,[PMDefaultTime]
--      ,[DownTime]
--      ,[ProcessTimeExtension]
--      ,[MachineCount]
--      ,[ProcessTimeDelay]
--      ,[IncludeInReport]
--      ,[PreactorMachineID]
--      ,[ProcessMachineID]
--      ,[PreactorProcessID]
--      ,[PreactorMachineNumber]
--      ,[PlanetTogetherMachineNumber]
--FROM [NAASPB-PRD04\SQL2014].Premise.Setup.[tblProcessMachines]
GO
