CREATE TABLE [dbo].[_mst_push]
(
[last_update_date] [datetime] NOT NULL,
[master_schedule_id] [float] NOT NULL,
[organization_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_number] [bigint] NULL,
[line_number] [bigint] NULL,
[conc_order_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[component_item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assembly_item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operation_seq_num] [float] NULL,
[operation_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[true_operation_seq_num] [float] NULL,
[true_operation_code] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[child_dj_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parent_dj_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[machine_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_machine_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regrouping_allowed] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[setup_start_date] [datetime] NULL,
[start_time_date] [datetime] NULL,
[end_time_date] [datetime] NULL,
[to_machine] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reel_size] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_date] [datetime] NULL,
[start_qty] [float] NULL,
[total_job_length] [float] NULL,
[group_id] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[staging_number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiber_set_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complete] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[scheduled] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[locked] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[machine_override] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
