CREATE TABLE [dbo].[_report_1e_job_data]
(
[last_update_date] [datetime] NOT NULL,
[Name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commitment] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerExternalId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductDescription] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promise_date UDF] [datetime] NULL,
[Qty] [float] NULL,
[ResourceNames] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PercentFinished] [int] NULL,
[ScheduledStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NeedDateTime] [datetime] NULL,
[EarliestDelivery] [datetime] NULL,
[ScheduledStartDateTime] [datetime] NULL,
[ScheduledEndDateTime] [datetime] NULL,
[Priority] [int] NULL,
[remake UDF] [bit] NULL,
[schedule_approved UDF] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schedule_approved_date UDF] [datetime] NULL,
[PromiseLateness UDF] [float] NULL,
[PromiseLate UDF] [bit] NULL,
[Bottlenecks] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiberSet UDF] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staging UDF] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Locked] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anchored] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnHold] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnHoldReason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HoldUntil] [datetime] NULL,
[Hot] [bit] NULL,
[HotReason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpectedSetupHours] [float] NULL,
[ExpectedRunHours] [float] NULL,
[ReportedSetupHours] [float] NULL,
[ReportedRunHours] [float] NULL,
[StandardHours] [float] NULL,
[SchedulingHours] [float] NULL,
[ScheduledSetupHours] [float] NULL,
[ScheduledRunHours] [float] NULL,
[ScheduledHours] [float] NULL,
[CalendarDurationHours] [float] NULL,
[JobDurationHours] [numeric] (17, 6) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
