CREATE TABLE [dbo].[Oracle_USAC_PO_SO]
(
[item_number] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchase_order_ln_shp] [varchar] (920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_id] [bigint] NULL,
[plan_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organization_id] [bigint] NULL,
[organization_name] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[collection_id] [bigint] NULL,
[occurrence] [float] NULL,
[po_so_last_update_date] [datetime] NULL,
[last_udpated_by_id] [bigint] NULL,
[last_updated_by] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[po_so_creation_date] [datetime] NULL,
[created_by_id] [bigint] NULL,
[last_update_login] [float] NULL,
[quantity_allocated] [float] NULL,
[sales_order_ln] [varchar] (610) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shop_order_status] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[end_so_ln] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_item] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_qty] [float] NULL,
[so_mult] [float] NULL,
[so_uom] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_sch_ship] [datetime] NULL,
[customer_name] [varchar] (360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[set_name] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[set_number] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shop_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spec_number] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mutl_number] [float] NULL,
[mult_length] [float] NULL,
[mult_uom] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tolerance] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reel_size] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[line_spec] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spc_machine] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spc_job] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schd_start_date] [datetime] NULL,
[schd_complete_date] [datetime] NULL,
[prt_paper] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printer] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed_qty] [float] NULL,
[completed_cuts] [float] NULL,
[po] [varchar] (920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[internal_promise_date] [datetime] NULL,
[created_by] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[collection] [float] NULL,
[entry_date] [datetime] NULL,
[so_item_desc] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_uom_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_weight] [float] NULL,
[so_weight_uom] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[so_product_category] [varchar] (245) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_item_desc] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_uom_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_weight] [float] NULL,
[inv_weight_uom] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inv_product_category] [varchar] (245) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_date] [datetime] NULL,
[last_update_date] [datetime] NULL
) ON [PRIMARY]
GO
