CREATE TABLE [dbo].[_report_1a_capacity_planning]
(
[last_update_date] [datetime] NOT NULL,
[master_schedule_id] [float] NOT NULL,
[conc_order_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[child_dj_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parent_dj_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_name] [varchar] (360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assembly_item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[component_item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[machine_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[setup_start_date] [datetime] NULL,
[start_time_date] [datetime] NULL,
[end_time_date] [datetime] NULL,
[Quantity] [float] NULL,
[total_job_length] [float] NULL,
[group_id] [bigint] NULL,
[staging_number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiber_set_id] [bigint] NULL,
[complete] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[scheduled] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CalendarDurationHrs] [float] NULL,
[WorkDurationHrs] [float] NULL,
[Order_NeedDate] [datetime] NULL,
[Order_ScheduledEndDate] [datetime] NULL,
[Order_PromiseDate] [datetime] NULL,
[Order_DaysPastPromise] [float] NULL,
[Order_DaysPastNeed] [float] NULL,
[ProductionStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dj_status] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_ScheduleApproved] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[schedule_ship_date] [datetime] NULL,
[Route] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
