CREATE SCHEMA [Setup]
AUTHORIZATION [dbo]
GO
GRANT EXECUTE ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RO]
GO
GRANT EXECUTE ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RW]
GO
DENY DELETE ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RW]
GO
GRANT INSERT ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RW]
GO
GRANT SELECT ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RW]
GO
GRANT UPDATE ON SCHEMA:: [Setup] TO [NAA\SPB_Scheduling_RW]
GO
